version: '3.9'

services:
  auth-service:
    build:
      context: .
      dockerfile: ./services/auth-service/Dockerfile
    volumes:
      - /app/node_modules                   
      - ./Shared_dataBase:/app/Shared_dataBase:rw
    environment:
      - JWT_SECRET=transcendence-secret-key
    ports:
      - "3001:3001"
    command: sh -c "
      cd /app/Shared_dataBase && 
      npm install sqlite3 --save && 
      cd /app && 
      node server.js"